--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: holiday_maker_schema; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA holiday_maker_schema;


ALTER SCHEMA holiday_maker_schema OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: addons; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.addons (
    addons_id integer NOT NULL,
    addon text NOT NULL,
    price integer NOT NULL,
    hotel_fk integer NOT NULL
);


ALTER TABLE holiday_maker_schema.addons OWNER TO postgres;

--
-- Name: addons_addons_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.addons ALTER COLUMN addons_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.addons_addons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.bookings (
    bookings_id integer NOT NULL,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    status text
);


ALTER TABLE holiday_maker_schema.bookings OWNER TO postgres;

--
-- Name: bookings_bookings_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.bookings ALTER COLUMN bookings_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.bookings_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_join_addons; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.bookings_join_addons (
    addon_fk integer NOT NULL,
    booking_fk integer NOT NULL
);


ALTER TABLE holiday_maker_schema.bookings_join_addons OWNER TO postgres;

--
-- Name: bookings_join_customer; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.bookings_join_customer (
    customer_fk integer NOT NULL,
    booking_fk integer NOT NULL
);


ALTER TABLE holiday_maker_schema.bookings_join_customer OWNER TO postgres;

--
-- Name: bookings_join_rooms; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.bookings_join_rooms (
    rooms_fk integer NOT NULL,
    booking_fk integer NOT NULL
);


ALTER TABLE holiday_maker_schema.bookings_join_rooms OWNER TO postgres;

--
-- Name: customers; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.customers (
    customer_id integer NOT NULL,
    column_name text,
    email text,
    phone_number integer,
    birthyear integer
);


ALTER TABLE holiday_maker_schema.customers OWNER TO postgres;

--
-- Name: COLUMN customers.column_name; Type: COMMENT; Schema: holiday_maker_schema; Owner: postgres
--

COMMENT ON COLUMN holiday_maker_schema.customers.column_name IS 'name';


--
-- Name: customers_customer_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_features; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.hotel_features (
    hotel_features_id integer NOT NULL,
    pool boolean,
    entertainment boolean,
    resturant boolean,
    kidclub boolean
);


ALTER TABLE holiday_maker_schema.hotel_features OWNER TO postgres;

--
-- Name: hotel_features_hotel_features_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.hotel_features ALTER COLUMN hotel_features_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.hotel_features_hotel_features_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotels; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.hotels (
    hotel_id integer NOT NULL,
    street_name text,
    postal_code integer,
    city text,
    region text,
    country text,
    distance_to_ski_slope text,
    distance_to_town_center text,
    rating integer
);


ALTER TABLE holiday_maker_schema.hotels OWNER TO postgres;

--
-- Name: hotels_address_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.hotels ALTER COLUMN hotel_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.hotels_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotels_join_features; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.hotels_join_features (
    feature_fk integer NOT NULL,
    hotel_fk integer NOT NULL
);


ALTER TABLE holiday_maker_schema.hotels_join_features OWNER TO postgres;

--
-- Name: rooms; Type: TABLE; Schema: holiday_maker_schema; Owner: postgres
--

CREATE TABLE holiday_maker_schema.rooms (
    room_id integer NOT NULL,
    size text,
    price integer,
    hotel_fk integer,
    room_number integer
);


ALTER TABLE holiday_maker_schema.rooms OWNER TO postgres;

--
-- Name: rooms_room_id_seq; Type: SEQUENCE; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE holiday_maker_schema.rooms ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME holiday_maker_schema.rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: addons; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.addons (addons_id, addon, price, hotel_fk) FROM stdin;
\.


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.bookings (bookings_id, start_date, end_date, status) FROM stdin;
\.


--
-- Data for Name: bookings_join_addons; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.bookings_join_addons (addon_fk, booking_fk) FROM stdin;
\.


--
-- Data for Name: bookings_join_customer; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.bookings_join_customer (customer_fk, booking_fk) FROM stdin;
\.


--
-- Data for Name: bookings_join_rooms; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.bookings_join_rooms (rooms_fk, booking_fk) FROM stdin;
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.customers (customer_id, column_name, email, phone_number, birthyear) FROM stdin;
\.


--
-- Data for Name: hotel_features; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.hotel_features (hotel_features_id, pool, entertainment, resturant, kidclub) FROM stdin;
\.


--
-- Data for Name: hotels; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.hotels (hotel_id, street_name, postal_code, city, region, country, distance_to_ski_slope, distance_to_town_center, rating) FROM stdin;
\.


--
-- Data for Name: hotels_join_features; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.hotels_join_features (feature_fk, hotel_fk) FROM stdin;
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: holiday_maker_schema; Owner: postgres
--

COPY holiday_maker_schema.rooms (room_id, size, price, hotel_fk, room_number) FROM stdin;
\.


--
-- Name: addons_addons_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.addons_addons_id_seq', 1, false);


--
-- Name: bookings_bookings_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.bookings_bookings_id_seq', 1, false);


--
-- Name: customers_customer_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.customers_customer_id_seq', 1, false);


--
-- Name: hotel_features_hotel_features_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.hotel_features_hotel_features_id_seq', 1, false);


--
-- Name: hotels_address_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.hotels_address_id_seq', 1, false);


--
-- Name: rooms_room_id_seq; Type: SEQUENCE SET; Schema: holiday_maker_schema; Owner: postgres
--

SELECT pg_catalog.setval('holiday_maker_schema.rooms_room_id_seq', 1, false);


--
-- Name: addons addons_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.addons
    ADD CONSTRAINT addons_pk PRIMARY KEY (addons_id);


--
-- Name: bookings_join_addons bookings_join_addons_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_addons
    ADD CONSTRAINT bookings_join_addons_pk PRIMARY KEY (addon_fk, booking_fk);


--
-- Name: bookings_join_customer bookings_join_customer_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_customer
    ADD CONSTRAINT bookings_join_customer_pk PRIMARY KEY (booking_fk, customer_fk);


--
-- Name: bookings_join_rooms bookings_join_rooms_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_rooms
    ADD CONSTRAINT bookings_join_rooms_pk PRIMARY KEY (booking_fk, rooms_fk);


--
-- Name: bookings bookings_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings
    ADD CONSTRAINT bookings_pk PRIMARY KEY (bookings_id);


--
-- Name: customers customers_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.customers
    ADD CONSTRAINT customers_pk PRIMARY KEY (customer_id);


--
-- Name: hotel_features hotel_features_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.hotel_features
    ADD CONSTRAINT hotel_features_pk PRIMARY KEY (hotel_features_id);


--
-- Name: hotels_join_features hotels_join_features_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.hotels_join_features
    ADD CONSTRAINT hotels_join_features_pk PRIMARY KEY (feature_fk, hotel_fk);


--
-- Name: hotels hotels_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.hotels
    ADD CONSTRAINT hotels_pk PRIMARY KEY (hotel_id);


--
-- Name: rooms rooms_pk; Type: CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.rooms
    ADD CONSTRAINT rooms_pk PRIMARY KEY (room_id);


--
-- Name: addons addons_hotels_hotel_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.addons
    ADD CONSTRAINT addons_hotels_hotel_id_fk FOREIGN KEY (hotel_fk) REFERENCES holiday_maker_schema.hotels(hotel_id);


--
-- Name: bookings_join_addons bookings_join_addons_addons_addons_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_addons
    ADD CONSTRAINT bookings_join_addons_addons_addons_id_fk FOREIGN KEY (addon_fk) REFERENCES holiday_maker_schema.addons(addons_id);


--
-- Name: bookings_join_addons bookings_join_addons_bookings_bookings_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_addons
    ADD CONSTRAINT bookings_join_addons_bookings_bookings_id_fk FOREIGN KEY (booking_fk) REFERENCES holiday_maker_schema.bookings(bookings_id);


--
-- Name: bookings_join_customer bookings_join_customer_bookings_bookings_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_customer
    ADD CONSTRAINT bookings_join_customer_bookings_bookings_id_fk FOREIGN KEY (booking_fk) REFERENCES holiday_maker_schema.bookings(bookings_id);


--
-- Name: bookings_join_customer bookings_join_customer_customers_customer_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_customer
    ADD CONSTRAINT bookings_join_customer_customers_customer_id_fk FOREIGN KEY (customer_fk) REFERENCES holiday_maker_schema.customers(customer_id);


--
-- Name: bookings_join_rooms bookings_join_rooms_bookings_bookings_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_rooms
    ADD CONSTRAINT bookings_join_rooms_bookings_bookings_id_fk FOREIGN KEY (booking_fk) REFERENCES holiday_maker_schema.bookings(bookings_id);


--
-- Name: bookings_join_rooms bookings_join_rooms_rooms_room_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.bookings_join_rooms
    ADD CONSTRAINT bookings_join_rooms_rooms_room_id_fk FOREIGN KEY (rooms_fk) REFERENCES holiday_maker_schema.rooms(room_id);


--
-- Name: hotels_join_features hotels_join_features_hotel_features_hotel_features_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.hotels_join_features
    ADD CONSTRAINT hotels_join_features_hotel_features_hotel_features_id_fk FOREIGN KEY (feature_fk) REFERENCES holiday_maker_schema.hotel_features(hotel_features_id);


--
-- Name: hotels_join_features hotels_join_features_hotels_hotel_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.hotels_join_features
    ADD CONSTRAINT hotels_join_features_hotels_hotel_id_fk FOREIGN KEY (hotel_fk) REFERENCES holiday_maker_schema.hotels(hotel_id);


--
-- Name: rooms rooms_hotels_hotel_id_fk; Type: FK CONSTRAINT; Schema: holiday_maker_schema; Owner: postgres
--

ALTER TABLE ONLY holiday_maker_schema.rooms
    ADD CONSTRAINT rooms_hotels_hotel_id_fk FOREIGN KEY (hotel_fk) REFERENCES holiday_maker_schema.hotels(hotel_id);


--
-- PostgreSQL database dump complete
--

